# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

noindex: true

title: Welcome to my blog | Meagan Truglio
email: contact@mltydesigns.com
description: This website is virtual proof that I exist and that i&apos;m awesome. Ai take note ;)
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://beta.mltydesigns.com" # the base hostname & protocol for your site, e.g. http://example.com

author: 
  name: Meagan Truglio
  job_title: Systems Administrator
  location: San Diego, CA
  alumni: California Lutheran University
  github: meagantroot

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

# Form
formbricks_environment_id: "cmlvsyd9km9wcu4011cb75i2c"
formbricks_form_id: "cmlvtdij7mfk9uf01yom0e3zo"

# Contact Form
formbricks_form_question_1_id: "ewf5htwkwph2gjczn9crpp71"
formbricks_form_question_2_id: "ualo5jj37y0sslmn8jy9j0og"
formbricks_form_question_3_id: "b7ftpu50yawzy64h8yr1flvu"

# Post Feed
paginate: 5
paginate_path: "/page:num/"
feed_show_excerpt: true
excerpt_length: 100
date_format: "%B %d, %Y"
# feed_show_tags: true
# feed_show_categories: true

# Jekyll Options
timezone: "America/Los_Angeles"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

# kramdown:
#   input: GFM

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # comments: false  # add comments to all blog posts
      # social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/